name: Sync to DF-oss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-public-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DF-oss-fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push updates to DF-oss
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add oss "https://${{ secrets.SYNC_PAT }}@github.com/DigitalFortressTeam/DF-oss.git"
          git push oss main:main --force
